### ISSUE TITLE
Small edits

### ISSUE THREAD

**Issue by doc-hex** [econoalchemist/COLDCARD-Paranoid#1]
- broken image `OK2sign.JPG`

Maybe I missed it, but I think it's important to state clearly at the top that in "paranoid mode" the COLDCARD shall never---in its entire life---be connected to a computer of any kind. It will always get power from COLDPOWER or similar. Sneakernet via MicroSD shall be used for firmware upgrades and PSBT transfers.

**Comment by econoalchemist** [comment]
Good call, got that note added along with a note about comparing addresses between the COLDCARD exported `.csv` file and Sparrow Wallet. Along with a couple other minor edits/image updates.
